workspace: "D:\\BlizzardGames\\D2R Reimagined Tools"

d2r_root: "D:\\BlizzardGames\\Diablo II Resurrected\\"
d2r_reimagined_mod_root: "$d2r_root\\mods\\Reimagined\\Reimagined.mpq\\"

d2rmm_root: "$workspace\\D2RMM 1.8.0\\"
d2rmm_reimagined_mod_path: "$d2rmm_root\\mods\\Reimagined\\"

d2r_beta_launcher_root: "$workspace\\Reimagined Beta Launcher for Non-Steam\\"
d2r_beta_launcher_mods_path: "$d2r_beta_launcher_root\\utils\\mods\\"

work_path: "$workspace\\mods\\Reimagined\\output"
original_path: "$workspace\\mods\\Reimagined\\original_excel"
